name: C/C++ CI

on:
  push:
    tags:
    - v*.*
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v2
    
    - name: CMake version
      run: cmake --version
    
    - name: Configure CMake
      shell: bash
      run: |
           cmake -S . -B build -DCMAKE_INSTALL_PREFIX=${PWD}/install
    
    - name: Make
      run: cmake --build build --config Release -j
      
    - name: Install
      run: cmake --build build --config Release -j --target install
      
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      # if: "!startsWith(github.ref, 'refs/heads')"
      with:
        name: build-${{ matrix.os }}
        path: install
        
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
    - name: Download Artifacts
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/download-artifact@v2
      
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # tag_name: ${{ github.ref }}  # ${{ github.ref }} is default
        name: Release ${{ github.ref }}
        draft: true
        prerelease: true
        # body_path: CHANGELOG.txt
        files: 'build-*'
